from setuptools import setup, find_packages

setup(
    name="frbeams",
    version="1.0.0",
    description="Facial Recognition Based Employee Attendance Management System",
    author="FRBEAMS Development Team",
    author_email="admin@frbeams.com",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "Flask==2.3.3",
        "Flask-SQLAlchemy==3.0.5",
        "Flask-Login==0.6.3",
        "Flask-WTF==1.1.1",
        "Flask-CORS==4.0.0",
        "Werkzeug==2.3.7",
        "PyMySQL==1.1.0",
        "cryptography==41.0.7",
        "opencv-python==4.8.1.78",
        "face-recognition==1.3.0",
        "numpy==1.24.3",
        "Pillow==10.0.1",
        "python-dotenv==1.0.0",
        "JWT==1.3.1",
        "PyJWT==2.8.0",
        "bcrypt==4.0.1",
        "pandas==2.1.1",
        "openpyxl==3.1.2",
        "reportlab==4.0.4",
        "matplotlib==3.7.2",
        "seaborn==0.12.2",
        "gunicorn==21.2.0",
    ],
    extras_require={
        "dev": [
            "pytest==7.4.2",
            "pytest-cov==4.1.0",
            "black==23.7.0",
            "flake8==6.0.0",
            "isort==5.12.0",
        ],
        "test": [
            "pytest==7.4.2",
            "pytest-cov==4.1.0",
            "pytest-mock==3.11.1",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Framework :: Flask",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Office/Business",
    ],
    keywords="facial-recognition attendance management flask opencv",
    project_urls={
        "Bug Reports": "https://github.com/frbeams/frbeams/issues",
        "Source": "https://github.com/frbeams/frbeams",
        "Documentation": "https://frbeams.readthedocs.io/",
    },
)
